### ISSUE TITLE
accessing request object from refresh_nonce_handler

### ISSUE THREAD

**Issue by kagesenshi** [morepath/more.jwtauth#8]
Hi,

seems like its not possible to access the request object from refresh_nonce_handler, so there are no way for refresh_nonce_handler to query app for nonce settings or access dbsession on requests.

would be good if the request object is always passed to this. or is there other methods to get current request object?

Thanks

**Comment by henri-hulski** [comment]
@kagesenshi Yeah that makes sense.
Please create a PR if you have time. 
Otherwise I will fix it later.

**Comment by henri-hulski** [comment]
Fixed in #9.
